apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-pod
  namespace: demo
  labels:
    name: demoApp
spec:
  containers:
  - name: kubernetes-demo-container
    image: hcwxd/kubernetes-demo
    ports:
      - containerPort: 3000
