apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
  namespace: demo
spec:
  replicas: 2
  selector:
    app: myweb
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: kubeguide/tomcat-app:v1
          ports:
          - containerPort: 8080
          env: 
          - name: MYSQL_SERVICE_HOST
            value: 169.169.253.143

